// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/micbunio/blog.proto

package blogs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comment struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId               int64    `protobuf:"varint,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetBlogId() int64 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *Comment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Blog struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{1}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Blog) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetBlogListRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogListRequest) Reset()         { *m = GetBlogListRequest{} }
func (m *GetBlogListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlogListRequest) ProtoMessage()    {}
func (*GetBlogListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{2}
}

func (m *GetBlogListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogListRequest.Unmarshal(m, b)
}
func (m *GetBlogListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogListRequest.Marshal(b, m, deterministic)
}
func (m *GetBlogListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogListRequest.Merge(m, src)
}
func (m *GetBlogListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlogListRequest.Size(m)
}
func (m *GetBlogListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogListRequest proto.InternalMessageInfo

func (m *GetBlogListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetBlogListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetBlogListResponse struct {
	Blogs                []*Blog  `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogListResponse) Reset()         { *m = GetBlogListResponse{} }
func (m *GetBlogListResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlogListResponse) ProtoMessage()    {}
func (*GetBlogListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{3}
}

func (m *GetBlogListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogListResponse.Unmarshal(m, b)
}
func (m *GetBlogListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogListResponse.Marshal(b, m, deterministic)
}
func (m *GetBlogListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogListResponse.Merge(m, src)
}
func (m *GetBlogListResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlogListResponse.Size(m)
}
func (m *GetBlogListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogListResponse proto.InternalMessageInfo

func (m *GetBlogListResponse) GetBlogs() []*Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

type GetBlogRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogRequest) Reset()         { *m = GetBlogRequest{} }
func (m *GetBlogRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlogRequest) ProtoMessage()    {}
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{4}
}

func (m *GetBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogRequest.Unmarshal(m, b)
}
func (m *GetBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogRequest.Marshal(b, m, deterministic)
}
func (m *GetBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogRequest.Merge(m, src)
}
func (m *GetBlogRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlogRequest.Size(m)
}
func (m *GetBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogRequest proto.InternalMessageInfo

func (m *GetBlogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogResponse) Reset()         { *m = GetBlogResponse{} }
func (m *GetBlogResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlogResponse) ProtoMessage()    {}
func (*GetBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{5}
}

func (m *GetBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogResponse.Unmarshal(m, b)
}
func (m *GetBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogResponse.Marshal(b, m, deterministic)
}
func (m *GetBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogResponse.Merge(m, src)
}
func (m *GetBlogResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlogResponse.Size(m)
}
func (m *GetBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogResponse proto.InternalMessageInfo

func (m *GetBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateCommentRequest struct {
	BlogId               int64    `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{6}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetBlogId() int64 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *CreateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCommentListRequest struct {
	BlogId               int64    `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentListRequest) Reset()         { *m = GetCommentListRequest{} }
func (m *GetCommentListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentListRequest) ProtoMessage()    {}
func (*GetCommentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{7}
}

func (m *GetCommentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentListRequest.Unmarshal(m, b)
}
func (m *GetCommentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentListRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentListRequest.Merge(m, src)
}
func (m *GetCommentListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentListRequest.Size(m)
}
func (m *GetCommentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentListRequest proto.InternalMessageInfo

func (m *GetCommentListRequest) GetBlogId() int64 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *GetCommentListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCommentListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetCommentListResponse struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCommentListResponse) Reset()         { *m = GetCommentListResponse{} }
func (m *GetCommentListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentListResponse) ProtoMessage()    {}
func (*GetCommentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3563712a6bf0590d, []int{8}
}

func (m *GetCommentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentListResponse.Unmarshal(m, b)
}
func (m *GetCommentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentListResponse.Marshal(b, m, deterministic)
}
func (m *GetCommentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentListResponse.Merge(m, src)
}
func (m *GetCommentListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentListResponse.Size(m)
}
func (m *GetCommentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentListResponse proto.InternalMessageInfo

func (m *GetCommentListResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*Comment)(nil), "blogs.Comment")
	proto.RegisterType((*Blog)(nil), "blogs.Blog")
	proto.RegisterType((*GetBlogListRequest)(nil), "blogs.GetBlogListRequest")
	proto.RegisterType((*GetBlogListResponse)(nil), "blogs.GetBlogListResponse")
	proto.RegisterType((*GetBlogRequest)(nil), "blogs.GetBlogRequest")
	proto.RegisterType((*GetBlogResponse)(nil), "blogs.GetBlogResponse")
	proto.RegisterType((*CreateCommentRequest)(nil), "blogs.CreateCommentRequest")
	proto.RegisterType((*GetCommentListRequest)(nil), "blogs.GetCommentListRequest")
	proto.RegisterType((*GetCommentListResponse)(nil), "blogs.GetCommentListResponse")
}

func init() { proto.RegisterFile("rpc/micbunio/blog.proto", fileDescriptor_3563712a6bf0590d) }

var fileDescriptor_3563712a6bf0590d = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x3f, 0x12, 0x37, 0x13, 0x11, 0xa4, 0xa5, 0x4d, 0x8d, 0x4b, 0x45, 0xf0, 0x29, 0xe2,
	0xe0, 0x48, 0xe1, 0x52, 0x89, 0x53, 0xd3, 0xa2, 0x0a, 0x09, 0x2e, 0x86, 0x13, 0x12, 0x54, 0x89,
	0x3d, 0x89, 0x56, 0xb2, 0xbd, 0xc1, 0xde, 0x20, 0x71, 0xe2, 0xd7, 0xf2, 0x3f, 0xd0, 0x7e, 0x19,
	0xdb, 0x71, 0x38, 0x70, 0xf3, 0xbc, 0x99, 0x7d, 0x6f, 0xe7, 0x3d, 0x2f, 0x5c, 0x96, 0xfb, 0x64,
	0x91, 0xd3, 0x64, 0x73, 0x28, 0x28, 0x5b, 0x6c, 0x32, 0xb6, 0x8b, 0xf6, 0x25, 0xe3, 0x8c, 0x0c,
	0xc4, 0x77, 0x15, 0x5c, 0xed, 0x18, 0xdb, 0x65, 0xb8, 0x90, 0xe0, 0xe6, 0xb0, 0x5d, 0x60, 0xbe,
	0xe7, 0x3f, 0xd5, 0x4c, 0xf8, 0x0b, 0xbc, 0x3b, 0x96, 0xe7, 0x58, 0x70, 0x32, 0x01, 0x9b, 0xa6,
	0xbe, 0x35, 0xb3, 0xe6, 0x4e, 0x6c, 0xd3, 0x94, 0x5c, 0x82, 0x27, 0x08, 0x1e, 0x69, 0xea, 0xdb,
	0x12, 0x1c, 0x8a, 0xf2, 0x7d, 0x4a, 0x08, 0xb8, 0xc5, 0x3a, 0x47, 0xdf, 0x99, 0x59, 0xf3, 0x51,
	0x2c, 0xbf, 0x89, 0x0f, 0x5e, 0xc2, 0x0a, 0x8e, 0x05, 0xf7, 0x5d, 0x09, 0x9b, 0x92, 0x5c, 0x03,
	0x24, 0x25, 0xae, 0x39, 0xa6, 0x8f, 0x6b, 0xee, 0x0f, 0x64, 0x73, 0xa4, 0x91, 0x5b, 0x1e, 0x22,
	0xb8, 0xab, 0x8c, 0xed, 0x8e, 0xd4, 0xcf, 0x61, 0xc0, 0x29, 0xcf, 0x50, 0x6a, 0x8f, 0x62, 0x55,
	0x34, 0x65, 0x9c, 0x7f, 0xc9, 0xb8, 0x5d, 0x99, 0x15, 0x90, 0x07, 0xe4, 0x42, 0xe9, 0x03, 0xad,
	0x78, 0x8c, 0xdf, 0x0f, 0x58, 0x71, 0x21, 0x92, 0xd1, 0x9c, 0x72, 0xad, 0xab, 0x0a, 0x32, 0x85,
	0x21, 0xdb, 0x6e, 0x2b, 0xe4, 0x66, 0x6f, 0x55, 0x85, 0x37, 0xf0, 0xac, 0xc5, 0x51, 0xed, 0x59,
	0x51, 0x21, 0x79, 0x05, 0xca, 0x68, 0xdf, 0x9a, 0x39, 0xf3, 0xf1, 0x72, 0x1c, 0xc9, 0x2a, 0x12,
	0x73, 0xb1, 0xea, 0x84, 0x33, 0x98, 0xe8, 0x93, 0x46, 0xb9, 0xb3, 0x6e, 0xb8, 0x84, 0xa7, 0xf5,
	0x84, 0xe6, 0x7d, 0x09, 0xae, 0x38, 0x2d, 0x87, 0x3a, 0xb4, 0xb2, 0x11, 0x7e, 0x85, 0xf3, 0x3b,
	0xb9, 0xa0, 0x4e, 0xd0, 0x70, 0x37, 0x82, 0xb3, 0x5a, 0xc1, 0x35, 0xdc, 0xb3, 0xdb, 0xee, 0xf5,
	0x44, 0x1a, 0x7e, 0x83, 0x8b, 0x07, 0xe4, 0x9a, 0xbb, 0xe9, 0xda, 0x49, 0xfe, 0xda, 0x4e, 0xbb,
	0xdf, 0x4e, 0xa7, 0x65, 0xe7, 0x3d, 0x4c, 0xbb, 0xfc, 0x7a, 0xf3, 0xd7, 0x70, 0x96, 0x28, 0xd8,
	0x98, 0x3a, 0xd1, 0xdb, 0x9b, 0x4d, 0xeb, 0xfe, 0xf2, 0xb7, 0x0d, 0x63, 0xe1, 0xc9, 0x27, 0x2c,
	0x7f, 0xd0, 0x04, 0xc9, 0x2d, 0x9c, 0x09, 0xae, 0xcf, 0xe2, 0xa2, 0xcf, 0xf5, 0xa9, 0xe3, 0xe4,
	0x83, 0xa0, 0xaf, 0xa5, 0xe5, 0xef, 0x61, 0xdc, 0x80, 0xff, 0x97, 0xe5, 0x06, 0x3c, 0x0d, 0x93,
	0x8b, 0xf6, 0x98, 0x39, 0x3d, 0xed, 0xc2, 0xb5, 0xfe, 0x93, 0x56, 0xae, 0xe4, 0xca, 0x6c, 0xdf,
	0x93, 0x76, 0x30, 0x8d, 0xd4, 0xfb, 0x8e, 0xcc, 0xfb, 0x8e, 0xde, 0x89, 0xf7, 0x4d, 0x3e, 0xca,
	0x7f, 0xae, 0x61, 0x2f, 0x79, 0xf1, 0x57, 0xef, 0x38, 0xd5, 0xe0, 0xfa, 0x44, 0x57, 0x5d, 0x6a,
	0x35, 0xfa, 0xe2, 0x45, 0x6f, 0xe5, 0xc4, 0x66, 0x28, 0x95, 0xde, 0xfc, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x35, 0xbc, 0x2b, 0xcf, 0x79, 0x04, 0x00, 0x00,
}
