// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: rpc/micbunio/service.proto

package micbunio

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuestbookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	HostUrl string `protobuf:"bytes,3,opt,name=host_url,json=hostUrl,proto3" json:"host_url,omitempty"`
}

func (x *CreateGuestbookRequest) Reset() {
	*x = CreateGuestbookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_micbunio_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGuestbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuestbookRequest) ProtoMessage() {}

func (x *CreateGuestbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_micbunio_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuestbookRequest.ProtoReflect.Descriptor instead.
func (*CreateGuestbookRequest) Descriptor() ([]byte, []int) {
	return file_rpc_micbunio_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuestbookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGuestbookRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateGuestbookRequest) GetHostUrl() string {
	if x != nil {
		return x.HostUrl
	}
	return ""
}

type Guestbook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Guestbook) Reset() {
	*x = Guestbook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_micbunio_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guestbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guestbook) ProtoMessage() {}

func (x *Guestbook) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_micbunio_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guestbook.ProtoReflect.Descriptor instead.
func (*Guestbook) Descriptor() ([]byte, []int) {
	return file_rpc_micbunio_service_proto_rawDescGZIP(), []int{1}
}

func (x *Guestbook) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guestbook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guestbook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Guestbook) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetGuestbookListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guestbooks []*Guestbook `protobuf:"bytes,1,rep,name=guestbooks,proto3" json:"guestbooks,omitempty"`
}

func (x *GetGuestbookListResponse) Reset() {
	*x = GetGuestbookListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_micbunio_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestbookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestbookListResponse) ProtoMessage() {}

func (x *GetGuestbookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_micbunio_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestbookListResponse.ProtoReflect.Descriptor instead.
func (*GetGuestbookListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_micbunio_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGuestbookListResponse) GetGuestbooks() []*Guestbook {
	if x != nil {
		return x.Guestbooks
	}
	return nil
}

type GetGuestbookListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit   int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	HostUrl string `protobuf:"bytes,3,opt,name=host_url,json=hostUrl,proto3" json:"host_url,omitempty"`
}

func (x *GetGuestbookListRequest) Reset() {
	*x = GetGuestbookListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_micbunio_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestbookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestbookListRequest) ProtoMessage() {}

func (x *GetGuestbookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_micbunio_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestbookListRequest.ProtoReflect.Descriptor instead.
func (*GetGuestbookListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_micbunio_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGuestbookListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGuestbookListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGuestbookListRequest) GetHostUrl() string {
	if x != nil {
		return x.HostUrl
	}
	return ""
}

var File_rpc_micbunio_service_proto protoreflect.FileDescriptor

var file_rpc_micbunio_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x69, 0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x69,
	0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68,
	0x6f, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x68, 0x0a, 0x09, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62,
	0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x4f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6d, 0x69, 0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f, 0x2e, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x22, 0x62, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f,
	0x73, 0x74, 0x55, 0x72, 0x6c, 0x32, 0xba, 0x01, 0x0a, 0x10, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21,
	0x2e, 0x6d, 0x69, 0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x69, 0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x75, 0x65, 0x73, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x20, 0x2e, 0x6d, 0x69, 0x63, 0x62, 0x75,
	0x6e, 0x69, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x65, 0x73, 0x74, 0x62,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x62, 0x75, 0x6e, 0x69, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_micbunio_service_proto_rawDescOnce sync.Once
	file_rpc_micbunio_service_proto_rawDescData = file_rpc_micbunio_service_proto_rawDesc
)

func file_rpc_micbunio_service_proto_rawDescGZIP() []byte {
	file_rpc_micbunio_service_proto_rawDescOnce.Do(func() {
		file_rpc_micbunio_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_micbunio_service_proto_rawDescData)
	})
	return file_rpc_micbunio_service_proto_rawDescData
}

var file_rpc_micbunio_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_micbunio_service_proto_goTypes = []interface{}{
	(*CreateGuestbookRequest)(nil),   // 0: micbunio.CreateGuestbookRequest
	(*Guestbook)(nil),                // 1: micbunio.Guestbook
	(*GetGuestbookListResponse)(nil), // 2: micbunio.GetGuestbookListResponse
	(*GetGuestbookListRequest)(nil),  // 3: micbunio.GetGuestbookListRequest
	(*empty.Empty)(nil),              // 4: google.protobuf.Empty
}
var file_rpc_micbunio_service_proto_depIdxs = []int32{
	1, // 0: micbunio.GetGuestbookListResponse.guestbooks:type_name -> micbunio.Guestbook
	3, // 1: micbunio.GuestbookService.GetGuestbookList:input_type -> micbunio.GetGuestbookListRequest
	0, // 2: micbunio.GuestbookService.CreateGuestbook:input_type -> micbunio.CreateGuestbookRequest
	2, // 3: micbunio.GuestbookService.GetGuestbookList:output_type -> micbunio.GetGuestbookListResponse
	4, // 4: micbunio.GuestbookService.CreateGuestbook:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_micbunio_service_proto_init() }
func file_rpc_micbunio_service_proto_init() {
	if File_rpc_micbunio_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_micbunio_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGuestbookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_micbunio_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guestbook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_micbunio_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestbookListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_micbunio_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestbookListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_micbunio_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_micbunio_service_proto_goTypes,
		DependencyIndexes: file_rpc_micbunio_service_proto_depIdxs,
		MessageInfos:      file_rpc_micbunio_service_proto_msgTypes,
	}.Build()
	File_rpc_micbunio_service_proto = out.File
	file_rpc_micbunio_service_proto_rawDesc = nil
	file_rpc_micbunio_service_proto_goTypes = nil
	file_rpc_micbunio_service_proto_depIdxs = nil
}
