version: "3"

tasks:
  default:
    cmds:
      - task -l

  tools:
    desc: Install tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
      - go install github.com/vektra/mockery/v2@v2.42.1
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  mockery:
    desc: Generate mocks
    cmds:
      - mockery --all

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./...

  coverage:
    desc: Run coverage
    cmds:
      - bash ./scripts/coverage.sh

  proto:
    desc: Generate protobuf
    cmds:
      - protoc --go_out=paths=source_relative:. --twirp_out=paths=source_relative:. rpc/micbunio/service.proto

  serve:
    desc: Run server
    cmds:
      - go run cmd/micbunio/main.go


